---
ID: "2dca83bd-f357-4d40-bee1-23a4dd87b4e0"
Parent: "4f554d94-f449-429c-9da0-187f316bc95e"
Template: "4f554d94-f449-429c-9da0-187f316bc95e"
Path: /sitecore/templates/Modules/Redirects/Redirect Map/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181009T070707Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
