---
ID: "bed35573-8bc2-4289-a1c1-402613c998ef"
Parent: "983b7159-2bef-4e32-b712-c3c78f8e3b53"
Template: "983b7159-2bef-4e32-b712-c3c78f8e3b53"
Path: /sitecore/templates/Modules/Redirects/Enums/__Standard Values
DB: master
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Type: TreelistEx
  Value: "{FED592AF-5C6F-457E-851E-1E92B4C5AD0C}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181009T072304Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
